### ISSUE TITLE
로그인 불가(`POST /api/login` `404` `알 수 없는 에러가 발생했습니다.\n관리자에게 문의해 주세요`)

### ISSUE THREAD

**Issue by sunrabbit123** [GSM-MSG/SMS-FrontEnd#287]
### Describe

요약
URL: https://sms.msg-team.com/api/login
상태: 404
소스: 네트워크
주소: 76.76.21.93:443
초기화 프로그램: 
_app-828c0aadebfaa51f.js:29:22172

요청
:method: POST
:scheme: https
:authority: sms.msg-team.com
:path: /api/login
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR,ko;q=0.9
Connection: keep-alive
Content-Length: 47
Content-Type: application/json
Host: sms.msg-team.com
Origin: https://sms.msg-team.com
Referer: https://sms.msg-team.com/login?code=d5762f52-be66-401b-a24f-80503937c7b1
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15

응답
:status: 404
Cache-Control: public, max-age=0, must-revalidate
Content-Length: 96
Content-Type: application/json; charset=utf-8
Date: Tue, 05 Dec 2023 15:28:18 GMT
ETag: "hwf9j67tug1c"
Server: Vercel
Strict-Transport-Security: max-age=63072000
x-matched-path: /api/login
x-vercel-cache: MISS
x-vercel-id: icn1::iad1::m765c-1701790098158-642018eef4d3

요청 데이터
MIME 유형: application/json
요청 데이터: 

### Additional

<img width="649" alt="스크린샷 2023-12-06 오전 12 45 17" src="https://github.com/GSM-MSG/SMS-FrontEnd/assets/64676070/ef194e37-18ce-4a4a-b29a-ac102ad76d17">

**Comment by chanwoo00106** [comment]
졸업자는 로그인을 할 수 없어서 생긴 문제입니다
