### ISSUE TITLE
로그인했을 때 학생의 정보가 제대로 표시되지 않는 현상

### ISSUE THREAD

**Issue by kimgh06** [GSM-MSG/SMS-FrontEnd#316]
### Describe

![image](https://github.com/GSM-MSG/SMS-FrontEnd/assets/101877146/32be1818-dd2b-40f4-879c-8f0fc6be2a59)
로그인을 해도 학생 정보가 블러 처리되서 나옴

**Comment by googoo81** [comment]
서버 응답속도 때문입니다.
